# Change these first
owner: leebaovn # Your GitHub organization or username, where this repository lives
repo: spotlight-status # The name of this repository

sites:
  - name: Spotlight API
    url: https://spotlight-staging.mirai-chi.com/users
    method: GET
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: spotlight-staging.mirai-chi.com
  baseUrl: /spotlight-status
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Spotlight status
  introTitle: BaoVoDich was here
  introMessage: Setting up this page to tracking the api status
  navbar:
    - title: Status
      href: /
    - title: Github
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
